Feature/body
coderhood-dev/team-ramen pull request #7
Opened 2020-12-05 21:58 UTC by mgs1422

En esta rama realice la UI y la funcionalidad de Home de la pagina, listando con primera instancia las peliculas mas populares luego mediante un select puedo seleccionar las peliculas por genero y luego cuando me muestra las peliculas puedo hacer click sobre ellas y me lleva al detalle de la pelicula donde se encuentra el boton comprar, esta funcionalidad hay que desarrollarla.

2020-12-08 22:41 UTC, emaLorenzo requested changes
Excelente trabajo @mgs1422! te dejo algunas correcciones

2020-12-08 22:41 UTC, emaLorenzo commented on src/components/GridMovies/GridMovies.js
> +  switch (id) {
Esta funcion la extraeria a una funcion en `/utils` que sea algo como `mapMovieGenders`

2020-12-08 22:41 UTC, emaLorenzo commented on src/components/GridMovies/GridMovies.js
> +    const doFetchCharacters = async () => {
porfa actualizate el nombre de la funcion para mantener el contexto

2020-12-08 22:41 UTC, emaLorenzo commented on src/components/GridMovies/GridMovies.js
> +        Peliculas de {TitleGenrer}
solo los componentes deberian estar en mayusculas, renombralo a minuscula porfa

2020-12-08 22:41 UTC, emaLorenzo commented on src/components/GridMovies/GridMovies.js
> +          onClick={() => ChangePreviusPage()}
mismo las funciones, siempre en minusculas

2020-12-08 22:41 UTC, emaLorenzo commented on src/components/GridMovies/GridMovies.js
> +          onClick={() => ChangeNextPage()}
esta tmb

2020-12-08 22:41 UTC, emaLorenzo commented on src/components/Home/Home.js
> +      <Background />
Aca no veo el sentido de usar Background en un componente aparte.. podria estar tranquilamente metido el contenido de Background aca adentro

2020-12-08 22:41 UTC, emaLorenzo commented on src/components/Home/Home.js
> +      <Background />
Aca no veo el sentido de usar Background en un componente aparte.. podria estar tranquilamente metido el contenido de Background aca adentro

2020-12-08 22:41 UTC, emaLorenzo commented on src/components/Image/Image.js
> +    <Flex bg="black" width={props.w} height="17.40rem">
Guarda que no estas extrayendo ({ w, ...props}), osea que en <ChakraImage {...props} <- tiene tambien la prop `w` esto es intencional?

2020-12-08 22:41 UTC, emaLorenzo commented on src/components/Image/Image.js
> +    <Flex bg="black" width={props.w} height="17.40rem">
Pregunto porque podrias estar queriendo darle un width al Flex, y se lo vas a estar dando tmb al Image

2020-12-08 22:41 UTC, emaLorenzo commented on src/components/NavBar/NavBar.js
> +  const handleGenres = (genre) => {
Extraer en una funcion aparte en `/utils`

2020-12-09 13:18 UTC, mgs1422 commented on src/components/GridMovies/GridMovies.js
> +  switch (id) {
Solucionado

2020-12-09 13:19 UTC, mgs1422 commented on src/components/GridMovies/GridMovies.js
> +    const doFetchCharacters = async () => {
Solucionado

2020-12-09 13:20 UTC, mgs1422 commented on src/components/GridMovies/GridMovies.js
> +        Peliculas de {TitleGenrer}
Solucionado

2020-12-09 13:21 UTC, mgs1422 commented on src/components/GridMovies/GridMovies.js
> +          onClick={() => ChangePreviusPage()}
Solucionado

2020-12-09 13:21 UTC, mgs1422 commented on src/components/GridMovies/GridMovies.js
> +          onClick={() => ChangeNextPage()}
Solucionado

2020-12-09 13:22 UTC, mgs1422 commented on src/components/Home/Home.js
> +      <Background />
Solucioando

2020-12-09 13:24 UTC, mgs1422 commented on src/components/Home/Home.js
> +      <Background />
Solucionado

2020-12-09 13:26 UTC, mgs1422 commented on src/components/Image/Image.js
> +    <Flex bg="black" width={props.w} height="17.40rem">
Si esto es intencional asi el Flex tiene el mismo tamaño que la Image

2020-12-09 13:27 UTC, mgs1422 commented on src/components/NavBar/NavBar.js
> +  const handleGenres = (genre) => {
Solucionado

2020-12-09 15:19 UTC, emaLorenzo approved these changes

2020-12-09 18:54 UTC, merged